% Adapted from rdf-prolog-roundtrip.
% This standalone program combines generated RDF input with its ISO Prolog rules.

% Generated by rdf-prolog-roundtrip.

% RDF terms use rdf(Subject, Predicate, Object, Graph).

rdf(iri('https://example.org/alpha_care_process'), iri('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'), iri('https://w3id.org/dpv#Process'), default_graph).
rdf(iri('https://example.org/alpha_care_process'), iri('https://w3id.org/dpv#hasDataController'), iri('https://example.org/hospital_a'), default_graph).
rdf(iri('https://example.org/alpha_care_process'), iri('https://w3id.org/dpv#hasRecipient'), iri('https://example.org/research_partner'), default_graph).
rdf(iri('https://example.org/alpha_care_process'), iri('https://w3id.org/dpv#hasPersonalData'), iri('https://example.org/lab_result'), default_graph).
rdf(iri('https://example.org/alpha_care_process'), iri('https://w3id.org/dpv#hasProcessing'), iri('https://w3id.org/dpv#Use'), default_graph).
rdf(iri('https://example.org/alpha_care_process'), iri('https://w3id.org/dpv#hasPurpose'), iri('https://w3id.org/dpv#Healthcare'), default_graph).
rdf(iri('https://example.org/alpha_care_process'), iri('https://w3id.org/dpv#hasLegalBasis'), iri('https://w3id.org/dpv#Consent'), default_graph).
rdf(iri('https://example.org/alpha_policy'), iri('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'), iri('http://www.w3.org/ns/odrl/2/Policy'), default_graph).
rdf(iri('https://example.org/alpha_policy'), iri('https://example.org/representsProcess'), iri('https://example.org/alpha_care_process'), default_graph).
rdf(iri('https://example.org/alpha_policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/alpha_permission'), default_graph).
rdf(iri('https://example.org/alpha_permission'), iri('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'), iri('http://www.w3.org/ns/odrl/2/Permission'), default_graph).
rdf(iri('https://example.org/alpha_permission'), iri('http://www.w3.org/ns/odrl/2/assigner'), iri('https://example.org/hospital_a'), default_graph).
rdf(iri('https://example.org/alpha_permission'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/research_partner'), default_graph).
rdf(iri('https://example.org/alpha_permission'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/lab_result'), default_graph).
rdf(iri('https://example.org/alpha_permission'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph).
rdf(iri('https://example.org/alpha_permission'), iri('http://www.w3.org/ns/odrl/2/constraint'), iri('https://example.org/alpha_purpose_constraint'), default_graph).
rdf(iri('https://example.org/alpha_permission'), iri('http://www.w3.org/ns/odrl/2/constraint'), iri('https://example.org/alpha_basis_constraint'), default_graph).
rdf(iri('https://example.org/alpha_purpose_constraint'), iri('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'), iri('http://www.w3.org/ns/odrl/2/Constraint'), default_graph).
rdf(iri('https://example.org/alpha_purpose_constraint'), iri('http://www.w3.org/ns/odrl/2/leftOperand'), iri('http://www.w3.org/ns/odrl/2/purpose'), default_graph).
rdf(iri('https://example.org/alpha_purpose_constraint'), iri('http://www.w3.org/ns/odrl/2/operator'), iri('http://www.w3.org/ns/odrl/2/isA'), default_graph).
rdf(iri('https://example.org/alpha_purpose_constraint'), iri('http://www.w3.org/ns/odrl/2/rightOperand'), iri('https://w3id.org/dpv#Healthcare'), default_graph).
rdf(iri('https://example.org/alpha_basis_constraint'), iri('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'), iri('http://www.w3.org/ns/odrl/2/Constraint'), default_graph).
rdf(iri('https://example.org/alpha_basis_constraint'), iri('http://www.w3.org/ns/odrl/2/leftOperand'), iri('https://example.org/legalBasis'), default_graph).
rdf(iri('https://example.org/alpha_basis_constraint'), iri('http://www.w3.org/ns/odrl/2/operator'), iri('http://www.w3.org/ns/odrl/2/isA'), default_graph).
rdf(iri('https://example.org/alpha_basis_constraint'), iri('http://www.w3.org/ns/odrl/2/rightOperand'), iri('https://w3id.org/dpv#Consent'), default_graph).

% The DPV process and ODRL policy are RDF data. The rules verify the six
% correspondences and return one deterministic mapping report.
%% goal: result_rdf(_, _, _, _)

dpv_odrl_purpose_mapping(Mappings) :-
  findall(
    mapping(SourceRole, Value, TargetRole),
    mapped_role(SourceRole, Value, TargetRole),
    Mappings
  ).

mapped_role(data_controller, Controller, assigner) :-
  rdf_link(ex(alpha_care_process), dpv(hasDataController), ex(Controller)),
  rdf_link(ex(alpha_permission), odrl(assigner), ex(Controller)).

mapped_role(recipient, Recipient, assignee) :-
  rdf_link(ex(alpha_care_process), dpv(hasRecipient), ex(Recipient)),
  rdf_link(ex(alpha_permission), odrl(assignee), ex(Recipient)).

mapped_role(personal_data, Data, target) :-
  rdf_link(ex(alpha_care_process), dpv(hasPersonalData), ex(Data)),
  rdf_link(ex(alpha_permission), odrl(target), ex(Data)).

mapped_role(processing, dpv_use, action) :-
  rdf_link(ex(alpha_care_process), dpv(hasProcessing), dpv('Use')),
  rdf_link(ex(alpha_permission), odrl(action), odrl(use)).

mapped_role(purpose, dpv_healthcare, constraint(alpha_purpose_constraint)) :-
  rdf_link(ex(alpha_care_process), dpv(hasPurpose), dpv('Healthcare')),
  odrl_constraint(alpha_purpose_constraint, odrl(purpose), dpv('Healthcare')).

mapped_role(legal_basis, dpv_consent, constraint(alpha_basis_constraint)) :-
  rdf_link(ex(alpha_care_process), dpv(hasLegalBasis), dpv('Consent')),
  odrl_constraint(alpha_basis_constraint, ex(legalBasis), dpv('Consent')).

odrl_constraint(Name, LeftOperand, RightOperand) :-
  rdf_link(ex(alpha_permission), odrl(constraint), ex(Name)),
  rdf_link(ex(Name), odrl('leftOperand'), LeftOperand),
  rdf_link(ex(Name), odrl(operator), odrl('isA')),
  rdf_link(ex(Name), odrl('rightOperand'), RightOperand).

rdf_link(Subject, Predicate, Object) :-
  iri_term(Subject, SubjectIri),
  iri_term(Predicate, PredicateIri),
  rdf(iri(SubjectIri), iri(PredicateIri), iri(ObjectIri), default_graph),
  iri_term(Object, ObjectIri).

iri_term(ex(Name), Iri) :- namespace_iri('https://example.org/', Name, Iri).
iri_term(dpv(Name), Iri) :- namespace_iri('https://w3id.org/dpv#', Name, Iri).
iri_term(odrl(Name), Iri) :- namespace_iri('http://www.w3.org/ns/odrl/2/', Name, Iri).

namespace_iri(Prefix, Name, Iri) :- atom_concat(Prefix, Name, Iri).

% RDF form of every verified DPV -> ODRL mapping.
result_rdf(iri(Node), iri('https://example.org/sourceRole'), iri(RoleIri), default_graph) :-
  mapped_role(Role, _Value, _Target),
  mapping_node(Role, Node),
  mapping_role_iri(Role, RoleIri).
result_rdf(iri(Node), iri('https://example.org/value'), iri(ValueIri), default_graph) :-
  mapped_role(Role, Value, _Target),
  mapping_node(Role, Node),
  mapping_value_iri(Role, Value, ValueIri).
result_rdf(iri(Node), iri('https://example.org/mappingTarget'), iri(TargetIri), default_graph) :-
  mapped_role(Role, _Value, Target),
  mapping_node(Role, Node),
  mapping_target_iri(Target, TargetIri).

mapping_node(Role, Iri) :- atom_concat('https://example.org/result/mapping/', Role, Iri).
mapping_role_iri(Role, Iri) :- atom_concat('https://example.org/role/', Role, Iri).

mapping_value_iri(data_controller, Value, Iri) :- iri_term(ex(Value), Iri).
mapping_value_iri(recipient, Value, Iri) :- iri_term(ex(Value), Iri).
mapping_value_iri(personal_data, Value, Iri) :- iri_term(ex(Value), Iri).
mapping_value_iri(processing, dpv_use, Iri) :- iri_term(dpv('Use'), Iri).
mapping_value_iri(purpose, dpv_healthcare, Iri) :- iri_term(dpv('Healthcare'), Iri).
mapping_value_iri(legal_basis, dpv_consent, Iri) :- iri_term(dpv('Consent'), Iri).

mapping_target_iri(assigner, Iri) :- iri_term(odrl(assigner), Iri).
mapping_target_iri(assignee, Iri) :- iri_term(odrl(assignee), Iri).
mapping_target_iri(target, Iri) :- iri_term(odrl(target), Iri).
mapping_target_iri(action, Iri) :- iri_term(odrl(action), Iri).
mapping_target_iri(constraint(Name), Iri) :- iri_term(ex(Name), Iri).

% ISO Prolog helper: print the complete test result as rdf/4 facts.
write_results :-
  result_rdf(S, P, O, G),
  write_term(rdf(S, P, O, G), [quoted(true)]),
  write('.'),
  nl,
  fail.
write_results.
