% Adapted from rdf-prolog-roundtrip.
% This standalone program combines generated RDF input with its ISO Prolog rules.

% Generated by rdf-prolog-roundtrip.

% RDF terms use rdf(Subject, Predicate, Object, Graph).

rdf(iri('https://example.org/consumer-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/delete-account'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/change-terms'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/share-data'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('http://www.w3.org/ns/odrl/2/prohibition'), iri('https://example.org/export-data'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/deletion-profile'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/terms-profile'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/sharing-profile'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/portability-profile'), default_graph).
rdf(iri('https://example.org/delete-account'), iri('https://example.org/clause'), literal('c1', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/delete-account'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/remove-account'), default_graph).
rdf(iri('https://example.org/change-terms'), iri('https://example.org/clause'), literal('c2', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/change-terms'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/change-terms-action'), default_graph).
rdf(iri('https://example.org/change-terms'), iri('http://www.w3.org/ns/odrl/2/duty'), iri('https://example.org/inform-duty'), default_graph).
rdf(iri('https://example.org/inform-duty'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/inform'), default_graph).
rdf(iri('https://example.org/change-terms'), iri('http://www.w3.org/ns/odrl/2/constraint'), iri('https://example.org/notice-constraint'), default_graph).
rdf(iri('https://example.org/notice-constraint'), iri('http://www.w3.org/ns/odrl/2/leftOperand'), iri('https://example.org/noticeDays'), default_graph).
rdf(iri('https://example.org/notice-constraint'), iri('http://www.w3.org/ns/odrl/2/operator'), iri('http://www.w3.org/ns/odrl/2/eq'), default_graph).
rdf(iri('https://example.org/notice-constraint'), iri('http://www.w3.org/ns/odrl/2/rightOperand'), literal('3', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/share-data'), iri('https://example.org/clause'), literal('c3', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/share-data'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/disclose'), default_graph).
rdf(iri('https://example.org/export-data'), iri('https://example.org/clause'), literal('c4', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/export-data'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/export'), default_graph).
rdf(iri('https://example.org/deletion-profile'), iri('https://example.org/risk'), iri('https://example.org/deletion-risk'), default_graph).
rdf(iri('https://example.org/deletion-profile'), iri('https://example.org/policyRule'), iri('https://example.org/delete-account'), default_graph).
rdf(iri('https://example.org/deletion-profile'), iri('https://example.org/need'), iri('https://example.org/no-deletion-without-notice'), default_graph).
rdf(iri('https://example.org/deletion-profile'), iri('https://example.org/baseScore'), literal('90', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/deletion-profile'), iri('https://example.org/mitigation'), iri('https://example.org/require-notice-before-deletion'), default_graph).
rdf(iri('https://example.org/terms-profile'), iri('https://example.org/risk'), iri('https://example.org/terms-risk'), default_graph).
rdf(iri('https://example.org/terms-profile'), iri('https://example.org/policyRule'), iri('https://example.org/change-terms'), default_graph).
rdf(iri('https://example.org/terms-profile'), iri('https://example.org/need'), iri('https://example.org/change-only-with-14-days-notice'), default_graph).
rdf(iri('https://example.org/terms-profile'), iri('https://example.org/baseScore'), literal('70', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/terms-profile'), iri('https://example.org/mitigation'), iri('https://example.org/require-14-days-notice'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/risk'), iri('https://example.org/sharing-risk'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/policyRule'), iri('https://example.org/share-data'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/need'), iri('https://example.org/no-sharing-without-consent'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/baseScore'), literal('85', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/mitigation'), iri('https://example.org/require-explicit-consent'), default_graph).
rdf(iri('https://example.org/portability-profile'), iri('https://example.org/risk'), iri('https://example.org/portability-risk'), default_graph).
rdf(iri('https://example.org/portability-profile'), iri('https://example.org/policyRule'), iri('https://example.org/export-data'), default_graph).
rdf(iri('https://example.org/portability-profile'), iri('https://example.org/need'), iri('https://example.org/data-portability'), default_graph).
rdf(iri('https://example.org/portability-profile'), iri('https://example.org/baseScore'), literal('60', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/portability-profile'), iri('https://example.org/mitigation'), iri('https://example.org/permit-data-export'), default_graph).
rdf(iri('https://example.org/no-deletion-without-notice'), iri('https://example.org/importance'), literal('20', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/change-only-with-14-days-notice'), iri('https://example.org/importance'), literal('15', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/change-only-with-14-days-notice'), iri('https://example.org/minimumNoticeDays'), literal('14', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/no-sharing-without-consent'), iri('https://example.org/importance'), literal('12', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/data-portability'), iri('https://example.org/importance'), literal('10', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).

% ODRL agreement rules and DPV-style needs are RDF data. The rules derive one
% risk per conflict, score it, and return one deterministic ranking.
%% goal: result_rdf(_, _, _, _)

consumer_risk_report(Ranked) :-
  findall(
    key(InverseScore, Clause)-dpv_risk(Risk, Score, Level, Clause, Mitigation),
    (
      risk_report(Risk, Score, Level, Clause, Mitigation),
      InverseScore is 1000 - Score
    ),
    Unsorted
  ),
  sort(Unsorted, Sorted),
  ranked_values(Sorted, 1, Ranked).

risk_report(Risk, Score, Level, Clause, Mitigation) :-
  risk_profile(_Profile, Risk, Rule, Need, Base, Mitigation),
  risk_triggered(Risk, Rule, Need),
  rdf_text(Rule, ex(clause), ClauseText),
  Clause = ClauseText,
  rdf_number(Need, ex(importance), Importance),
  Raw is Base + Importance,
  (Raw > 100 -> Score = 100 ; Score = Raw),
  risk_level(Score, Level).

risk_profile(Profile, Risk, Rule, Need, Base, Mitigation) :-
  rdf_link(ex('consumer-policy'), ex(riskProfile), Profile),
  rdf_link(Profile, ex(risk), RiskResource),
  risk_resource(Risk, RiskResource),
  rdf_link(Profile, ex(policyRule), Rule),
  rdf_link(Profile, ex(need), Need),
  rdf_number(Profile, ex(baseScore), Base),
  rdf_link(Profile, ex(mitigation), MitigationResource),
  mitigation_resource(Mitigation, MitigationResource).

risk_triggered(deletion_risk, Rule, _Need) :-
  rdf_link(ex('consumer-policy'), odrl(permission), Rule),
  rdf_link(Rule, odrl(action), ex('remove-account')),
  \+ duty_action(Rule, ex(inform)),
  \+ constraint_number(Rule, ex(noticeDays), _Days).

risk_triggered(terms_risk, Rule, Need) :-
  rdf_link(ex('consumer-policy'), odrl(permission), Rule),
  rdf_link(Rule, odrl(action), ex('change-terms-action')),
  duty_action(Rule, ex(inform)),
  constraint_number(Rule, ex(noticeDays), Days),
  rdf_number(Need, ex(minimumNoticeDays), Minimum),
  Days < Minimum.

risk_triggered(sharing_risk, Rule, _Need) :-
  rdf_link(ex('consumer-policy'), odrl(permission), Rule),
  rdf_link(Rule, odrl(action), ex(disclose)),
  \+ constraint_text(Rule, ex(explicitConsent), 'true').

risk_triggered(portability_risk, Rule, _Need) :-
  rdf_link(ex('consumer-policy'), odrl(prohibition), Rule),
  rdf_link(Rule, odrl(action), ex(export)).

duty_action(Rule, Action) :-
  rdf_link(Rule, odrl(duty), Duty),
  rdf_link(Duty, odrl(action), Action).

constraint_text(Rule, LeftOperand, Value) :-
  rdf_link(Rule, odrl(constraint), Constraint),
  rdf_link(Constraint, odrl('leftOperand'), LeftOperand),
  rdf_link(Constraint, odrl(operator), odrl(eq)),
  rdf_text(Constraint, odrl('rightOperand'), Value).

constraint_number(Rule, LeftOperand, Number) :-
  constraint_text(Rule, LeftOperand, Text),
  atom_chars(Text, Chars),
  number_chars(Number, Chars).

risk_level(Score, high) :- Score > 79.
risk_level(Score, moderate) :- Score > 49, Score < 80.

ranked_values([], _Rank, []).
ranked_values([_Key-Risk|Rest], Rank, [rank(Rank, Risk)|Ranked]) :-
  NextRank is Rank + 1,
  ranked_values(Rest, NextRank, Ranked).

risk_resource(deletion_risk, ex('deletion-risk')).
risk_resource(terms_risk, ex('terms-risk')).
risk_resource(sharing_risk, ex('sharing-risk')).
risk_resource(portability_risk, ex('portability-risk')).

mitigation_resource(require_notice_before_deletion, ex('require-notice-before-deletion')).
mitigation_resource(require_14_days_notice, ex('require-14-days-notice')).
mitigation_resource(require_explicit_consent, ex('require-explicit-consent')).
mitigation_resource(permit_data_export, ex('permit-data-export')).

rdf_link(Subject, Predicate, Object) :-
  iri_term(Subject, SubjectIri),
  iri_term(Predicate, PredicateIri),
  rdf(iri(SubjectIri), iri(PredicateIri), iri(ObjectIri), default_graph),
  iri_term(Object, ObjectIri).

rdf_text(Subject, Predicate, Text) :-
  iri_term(Subject, SubjectIri),
  iri_term(Predicate, PredicateIri),
  rdf(iri(SubjectIri), iri(PredicateIri), literal(Text, datatype(_Datatype)), default_graph).

rdf_number(Subject, Predicate, Number) :-
  rdf_text(Subject, Predicate, Text),
  atom_chars(Text, Chars),
  number_chars(Number, Chars).

iri_term(ex(Name), Iri) :- namespace_iri('https://example.org/', Name, Iri).
iri_term(odrl(Name), Iri) :- namespace_iri('http://www.w3.org/ns/odrl/2/', Name, Iri).

namespace_iri(Prefix, Name, Iri) :- atom_concat(Prefix, Name, Iri).

% RDF form of the ranked consumer risks.
result_rdf(iri(RiskIri), iri('https://example.org/rank'), literal(RankText, datatype('http://www.w3.org/2001/XMLSchema#integer')), default_graph) :-
  consumer_ranked_item(Rank, Risk, _Score, _Level, _Clause, _Mitigation),
  risk_resource(Risk, RiskTerm), iri_term(RiskTerm, RiskIri), number_atom(Rank, RankText).
result_rdf(iri(RiskIri), iri('https://example.org/score'), literal(ScoreText, datatype('http://www.w3.org/2001/XMLSchema#integer')), default_graph) :-
  consumer_ranked_item(_Rank, Risk, Score, _Level, _Clause, _Mitigation),
  risk_resource(Risk, RiskTerm), iri_term(RiskTerm, RiskIri), number_atom(Score, ScoreText).
result_rdf(iri(RiskIri), iri('https://example.org/level'), iri(LevelIri), default_graph) :-
  consumer_ranked_item(_Rank, Risk, _Score, Level, _Clause, _Mitigation),
  risk_resource(Risk, RiskTerm), iri_term(RiskTerm, RiskIri), atom_concat('https://example.org/', Level, LevelIri).
result_rdf(iri(RiskIri), iri('https://example.org/clause'), literal(Clause, datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph) :-
  consumer_ranked_item(_Rank, Risk, _Score, _Level, Clause, _Mitigation),
  risk_resource(Risk, RiskTerm), iri_term(RiskTerm, RiskIri).
result_rdf(iri(RiskIri), iri('https://example.org/mitigation'), iri(MitigationIri), default_graph) :-
  consumer_ranked_item(_Rank, Risk, _Score, _Level, _Clause, Mitigation),
  risk_resource(Risk, RiskTerm), iri_term(RiskTerm, RiskIri),
  mitigation_resource(Mitigation, MitigationTerm), iri_term(MitigationTerm, MitigationIri).

consumer_ranked_item(Rank, Risk, Score, Level, Clause, Mitigation) :-
  consumer_risk_report(Ranked),
  list_member(rank(Rank, dpv_risk(Risk, Score, Level, Clause, Mitigation)), Ranked).
list_member(X, [X|_]).
list_member(X, [_|Xs]) :- list_member(X, Xs).
number_atom(Number, Atom) :- number_chars(Number, Chars), atom_chars(Atom, Chars).

% ISO Prolog helper: print the complete test result as rdf/4 facts.
write_results :-
  result_rdf(S, P, O, G),
  write_term(rdf(S, P, O, G), [quoted(true)]),
  write('.'),
  nl,
  fail.
write_results.
