% Adapted from rdf-prolog-roundtrip.
% This standalone program combines generated RDF input with its ISO Prolog rules.

% Generated by rdf-prolog-roundtrip.

% RDF terms use rdf(Subject, Predicate, Object, Graph).

rdf(iri('https://example.org/healthcare-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/research-use'), default_graph).
rdf(iri('https://example.org/healthcare-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/genomic-sharing'), default_graph).
rdf(iri('https://example.org/healthcare-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/record-retention'), default_graph).
rdf(iri('https://example.org/healthcare-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/consent-profile'), default_graph).
rdf(iri('https://example.org/healthcare-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/sharing-profile'), default_graph).
rdf(iri('https://example.org/healthcare-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/retention-profile'), default_graph).
rdf(iri('https://example.org/research-use'), iri('https://example.org/clause'), literal('h1', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/research-use'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph).
rdf(iri('https://example.org/genomic-sharing'), iri('https://example.org/clause'), literal('h2', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/genomic-sharing'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/disclose'), default_graph).
rdf(iri('https://example.org/genomic-sharing'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/genomic-data'), default_graph).
rdf(iri('https://example.org/record-retention'), iri('https://example.org/clause'), literal('h4', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/record-retention'), iri('http://www.w3.org/ns/odrl/2/constraint'), iri('https://example.org/retention-constraint'), default_graph).
rdf(iri('https://example.org/retention-constraint'), iri('http://www.w3.org/ns/odrl/2/leftOperand'), iri('https://example.org/retentionDays'), default_graph).
rdf(iri('https://example.org/retention-constraint'), iri('http://www.w3.org/ns/odrl/2/operator'), iri('http://www.w3.org/ns/odrl/2/eq'), default_graph).
rdf(iri('https://example.org/retention-constraint'), iri('http://www.w3.org/ns/odrl/2/rightOperand'), literal('3650', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/consent-profile'), iri('https://example.org/risk'), iri('https://example.org/consent-risk'), default_graph).
rdf(iri('https://example.org/consent-profile'), iri('https://example.org/policyRule'), iri('https://example.org/research-use'), default_graph).
rdf(iri('https://example.org/consent-profile'), iri('https://example.org/need'), iri('https://example.org/explicit-consent-for-research'), default_graph).
rdf(iri('https://example.org/consent-profile'), iri('https://example.org/baseScore'), literal('85', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/consent-profile'), iri('https://example.org/mitigation'), iri('https://example.org/require-explicit-consent'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/risk'), iri('https://example.org/sharing-risk'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/policyRule'), iri('https://example.org/genomic-sharing'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/need'), iri('https://example.org/deidentify-before-sharing'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/baseScore'), literal('90', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/mitigation'), iri('https://example.org/require-deidentification'), default_graph).
rdf(iri('https://example.org/retention-profile'), iri('https://example.org/risk'), iri('https://example.org/retention-risk'), default_graph).
rdf(iri('https://example.org/retention-profile'), iri('https://example.org/policyRule'), iri('https://example.org/record-retention'), default_graph).
rdf(iri('https://example.org/retention-profile'), iri('https://example.org/need'), iri('https://example.org/retention-limit-3-years'), default_graph).
rdf(iri('https://example.org/retention-profile'), iri('https://example.org/baseScore'), literal('55', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/retention-profile'), iri('https://example.org/mitigation'), iri('https://example.org/limit-retention-to-1095-days'), default_graph).
rdf(iri('https://example.org/explicit-consent-for-research'), iri('https://example.org/importance'), literal('35', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/deidentify-before-sharing'), iri('https://example.org/importance'), literal('35', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/retention-limit-3-years'), iri('https://example.org/importance'), literal('15', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/retention-limit-3-years'), iri('https://example.org/maximumDays'), literal('1095', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).

% ODRL permissions and DPV-style risk profiles are RDF data. The rules detect
% missing safeguards, score the risks, and return one deterministic ranking.
%% goal: result_rdf(_, _, _, _)

healthcare_risk_report(Ranked) :-
  findall(
    key(InverseScore, Clause)-dpv_risk(Risk, Score, Level, Clause, Mitigation),
    (
      risk_report(Risk, Score, Level, Clause, Mitigation),
      InverseScore is 1000 - Score
    ),
    Unsorted
  ),
  sort(Unsorted, Sorted),
  ranked_values(Sorted, 1, Ranked).

risk_report(Risk, Score, Level, Clause, Mitigation) :-
  risk_profile(_Profile, Risk, Rule, Need, Base, Mitigation),
  risk_triggered(Risk, Rule, Need),
  rdf_text(Rule, ex(clause), ClauseText),
  Clause = ClauseText,
  rdf_number(Need, ex(importance), Importance),
  Raw is Base + Importance,
  (Raw > 100 -> Score = 100 ; Score = Raw),
  risk_level(Score, Level).

risk_profile(Profile, Risk, Rule, Need, Base, Mitigation) :-
  rdf_link(ex('healthcare-policy'), ex(riskProfile), Profile),
  rdf_link(Profile, ex(risk), RiskResource),
  risk_resource(Risk, RiskResource),
  rdf_link(Profile, ex(policyRule), Rule),
  rdf_link(Profile, ex(need), Need),
  rdf_number(Profile, ex(baseScore), Base),
  rdf_link(Profile, ex(mitigation), MitigationResource),
  mitigation_resource(Mitigation, MitigationResource).

risk_triggered(consent_risk, Rule, _Need) :-
  rdf_link(ex('healthcare-policy'), odrl(permission), Rule),
  rdf_link(Rule, odrl(action), odrl(use)),
  \+ constraint_text(Rule, ex(explicitConsent), 'true').

risk_triggered(sharing_risk, Rule, _Need) :-
  rdf_link(ex('healthcare-policy'), odrl(permission), Rule),
  rdf_link(Rule, odrl(action), ex(disclose)),
  rdf_link(Rule, odrl(target), ex('genomic-data')),
  \+ constraint_text(Rule, ex(deidentified), 'true').

risk_triggered(retention_risk, Rule, Need) :-
  rdf_link(ex('healthcare-policy'), odrl(permission), Rule),
  constraint_number(Rule, ex(retentionDays), Days),
  rdf_number(Need, ex(maximumDays), Maximum),
  Days > Maximum.

constraint_text(Rule, LeftOperand, Value) :-
  rdf_link(Rule, odrl(constraint), Constraint),
  rdf_link(Constraint, odrl('leftOperand'), LeftOperand),
  rdf_link(Constraint, odrl(operator), odrl(eq)),
  rdf_text(Constraint, odrl('rightOperand'), Value).

constraint_number(Rule, LeftOperand, Number) :-
  constraint_text(Rule, LeftOperand, Text),
  atom_chars(Text, Chars),
  number_chars(Number, Chars).

risk_level(Score, high) :- Score > 79.
risk_level(Score, moderate) :- Score > 49, Score < 80.

ranked_values([], _Rank, []).
ranked_values([_Key-Risk|Rest], Rank, [rank(Rank, Risk)|Ranked]) :-
  NextRank is Rank + 1,
  ranked_values(Rest, NextRank, Ranked).

risk_resource(consent_risk, ex('consent-risk')).
risk_resource(sharing_risk, ex('sharing-risk')).
risk_resource(retention_risk, ex('retention-risk')).

mitigation_resource(require_explicit_consent, ex('require-explicit-consent')).
mitigation_resource(require_deidentification, ex('require-deidentification')).
mitigation_resource(limit_retention_to_1095_days, ex('limit-retention-to-1095-days')).

rdf_link(Subject, Predicate, Object) :-
  iri_term(Subject, SubjectIri),
  iri_term(Predicate, PredicateIri),
  rdf(iri(SubjectIri), iri(PredicateIri), iri(ObjectIri), default_graph),
  iri_term(Object, ObjectIri).

rdf_text(Subject, Predicate, Text) :-
  iri_term(Subject, SubjectIri),
  iri_term(Predicate, PredicateIri),
  rdf(iri(SubjectIri), iri(PredicateIri), literal(Text, datatype(_Datatype)), default_graph).

rdf_number(Subject, Predicate, Number) :-
  rdf_text(Subject, Predicate, Text),
  atom_chars(Text, Chars),
  number_chars(Number, Chars).

iri_term(ex(Name), Iri) :- namespace_iri('https://example.org/', Name, Iri).
iri_term(odrl(Name), Iri) :- namespace_iri('http://www.w3.org/ns/odrl/2/', Name, Iri).

namespace_iri(Prefix, Name, Iri) :- atom_concat(Prefix, Name, Iri).

% RDF form of the ranked healthcare risks.
result_rdf(iri(RiskIri), iri('https://example.org/rank'), literal(RankText, datatype('http://www.w3.org/2001/XMLSchema#integer')), default_graph) :-
  healthcare_ranked_item(Rank, Risk, _Score, _Level, _Clause, _Mitigation),
  risk_resource(Risk, RiskTerm), iri_term(RiskTerm, RiskIri), number_atom(Rank, RankText).
result_rdf(iri(RiskIri), iri('https://example.org/score'), literal(ScoreText, datatype('http://www.w3.org/2001/XMLSchema#integer')), default_graph) :-
  healthcare_ranked_item(_Rank, Risk, Score, _Level, _Clause, _Mitigation),
  risk_resource(Risk, RiskTerm), iri_term(RiskTerm, RiskIri), number_atom(Score, ScoreText).
result_rdf(iri(RiskIri), iri('https://example.org/level'), iri(LevelIri), default_graph) :-
  healthcare_ranked_item(_Rank, Risk, _Score, Level, _Clause, _Mitigation),
  risk_resource(Risk, RiskTerm), iri_term(RiskTerm, RiskIri), atom_concat('https://example.org/', Level, LevelIri).
result_rdf(iri(RiskIri), iri('https://example.org/clause'), literal(Clause, datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph) :-
  healthcare_ranked_item(_Rank, Risk, _Score, _Level, Clause, _Mitigation),
  risk_resource(Risk, RiskTerm), iri_term(RiskTerm, RiskIri).
result_rdf(iri(RiskIri), iri('https://example.org/mitigation'), iri(MitigationIri), default_graph) :-
  healthcare_ranked_item(_Rank, Risk, _Score, _Level, _Clause, Mitigation),
  risk_resource(Risk, RiskTerm), iri_term(RiskTerm, RiskIri),
  mitigation_resource(Mitigation, MitigationTerm), iri_term(MitigationTerm, MitigationIri).

healthcare_ranked_item(Rank, Risk, Score, Level, Clause, Mitigation) :-
  healthcare_risk_report(Ranked),
  list_member(rank(Rank, dpv_risk(Risk, Score, Level, Clause, Mitigation)), Ranked).
list_member(X, [X|_]).
list_member(X, [_|Xs]) :- list_member(X, Xs).
number_atom(Number, Atom) :- number_chars(Number, Chars), atom_chars(Atom, Chars).

% ISO Prolog helper: print the complete test result as rdf/4 facts.
write_results :-
  result_rdf(S, P, O, G),
  write_term(rdf(S, P, O, G), [quoted(true)]),
  write('.'),
  nl,
  fail.
write_results.
