% Adapted from rdf-prolog-roundtrip.
% This standalone program combines generated RDF input with its ISO Prolog rules.

% Generated by rdf-prolog-roundtrip.

% RDF terms use rdf(Subject, Predicate, Object, Graph).

rdf(iri('https://example.org/advanced-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/research-permission'), default_graph).
rdf(iri('https://example.org/advanced-policy'), iri('http://www.w3.org/ns/odrl/2/prohibition'), iri('https://example.org/transfer-prohibition'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/health-dataset'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/research-hospital'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/constraint'), iri('https://example.org/purpose-constraint'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/constraint'), iri('https://example.org/region-constraint'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/duty'), iri('https://example.org/deidentify-duty'), default_graph).
rdf(iri('https://example.org/purpose-constraint'), iri('http://www.w3.org/ns/odrl/2/leftOperand'), iri('http://www.w3.org/ns/odrl/2/purpose'), default_graph).
rdf(iri('https://example.org/purpose-constraint'), iri('http://www.w3.org/ns/odrl/2/operator'), iri('http://www.w3.org/ns/odrl/2/eq'), default_graph).
rdf(iri('https://example.org/purpose-constraint'), iri('http://www.w3.org/ns/odrl/2/rightOperand'), iri('https://example.org/medical-research'), default_graph).
rdf(iri('https://example.org/region-constraint'), iri('http://www.w3.org/ns/odrl/2/leftOperand'), iri('http://www.w3.org/ns/odrl/2/spatial'), default_graph).
rdf(iri('https://example.org/region-constraint'), iri('http://www.w3.org/ns/odrl/2/operator'), iri('http://www.w3.org/ns/odrl/2/eq'), default_graph).
rdf(iri('https://example.org/region-constraint'), iri('http://www.w3.org/ns/odrl/2/rightOperand'), iri('https://example.org/eu'), default_graph).
rdf(iri('https://example.org/deidentify-duty'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/deidentify'), default_graph).
rdf(iri('https://example.org/transfer-prohibition'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/health-dataset'), default_graph).
rdf(iri('https://example.org/transfer-prohibition'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/transfer'), default_graph).
rdf(iri('https://example.org/transfer-prohibition'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/research-hospital'), default_graph).

% One policy is evaluated against three requests. The report demonstrates a
% constrained permission with a duty, a failed purpose constraint, and an
% explicit prohibition.
%% goal: result_rdf(_, _, _, _)

request(research_use, research_hospital, use, health_dataset, medical_research, eu).
request(commercial_use, research_hospital, use, health_dataset, commercial, eu).
request(dataset_transfer, research_hospital, transfer, health_dataset, medical_research, eu).

advanced_odrl_report([Research, Commercial, Transfer]) :-
  policy_decision(research_use, Research),
  policy_decision(commercial_use, Commercial),
  policy_decision(dataset_transfer, Transfer).

policy_decision(Request, decision(Request, permit, [duty(DutyAction)])) :-
  permitted(Request, DutyAction).
policy_decision(Request, decision(Request, deny, [reason(purpose_mismatch)])) :-
  purpose_mismatch(Request).
policy_decision(Request, decision(Request, deny, [reason(prohibited)])) :-
  prohibited(Request).

permitted(Request, DutyAction) :-
  request(Request, Assignee, Action, Target, Purpose, Region),
  rdf_link(advanced_policy, permission, Permission),
  rule_scope(Permission, Assignee, Action, Target),
  constraint_eq(Permission, purpose, Purpose),
  constraint_eq(Permission, spatial, Region),
  rdf_link(Permission, duty, Duty),
  rdf_link(Duty, action, DutyAction).

purpose_mismatch(Request) :-
  request(Request, Assignee, Action, Target, Purpose, Region),
  rdf_link(advanced_policy, permission, Permission),
  rule_scope(Permission, Assignee, Action, Target),
  constraint_eq(Permission, spatial, Region),
  constraint_eq(Permission, purpose, RequiredPurpose),
  Purpose \= RequiredPurpose.

prohibited(Request) :-
  request(Request, Assignee, Action, Target, _Purpose, _Region),
  rdf_link(advanced_policy, prohibition, Prohibition),
  rule_scope(Prohibition, Assignee, Action, Target).

rule_scope(Rule, Assignee, Action, Target) :-
  rdf_link(Rule, assignee, Assignee),
  rdf_link(Rule, action, Action),
  rdf_link(Rule, target, Target).

constraint_eq(Rule, LeftOperand, RightOperand) :-
  rdf_link(Rule, constraint, Constraint),
  rdf_link(Constraint, left_operand, LeftOperand),
  rdf_link(Constraint, operator, eq),
  rdf_link(Constraint, right_operand, RightOperand).

rdf_link(Subject, Predicate, Object) :-
  iri_value(Subject, SubjectIri),
  iri_value(Predicate, PredicateIri),
  iri_value(Object, ObjectIri),
  rdf(iri(SubjectIri), iri(PredicateIri), iri(ObjectIri), default_graph).

iri_value(advanced_policy, 'https://example.org/advanced-policy').
iri_value(research_permission, 'https://example.org/research-permission').
iri_value(transfer_prohibition, 'https://example.org/transfer-prohibition').
iri_value(health_dataset, 'https://example.org/health-dataset').
iri_value(research_hospital, 'https://example.org/research-hospital').
iri_value(medical_research, 'https://example.org/medical-research').
iri_value(eu, 'https://example.org/eu').
iri_value(deidentify_duty, 'https://example.org/deidentify-duty').
iri_value(deidentify, 'https://example.org/deidentify').
iri_value(purpose_constraint, 'https://example.org/purpose-constraint').
iri_value(region_constraint, 'https://example.org/region-constraint').
iri_value(permission, 'http://www.w3.org/ns/odrl/2/permission').
iri_value(prohibition, 'http://www.w3.org/ns/odrl/2/prohibition').
iri_value(target, 'http://www.w3.org/ns/odrl/2/target').
iri_value(action, 'http://www.w3.org/ns/odrl/2/action').
iri_value(assignee, 'http://www.w3.org/ns/odrl/2/assignee').
iri_value(constraint, 'http://www.w3.org/ns/odrl/2/constraint').
iri_value(duty, 'http://www.w3.org/ns/odrl/2/duty').
iri_value(left_operand, 'http://www.w3.org/ns/odrl/2/leftOperand').
iri_value(operator, 'http://www.w3.org/ns/odrl/2/operator').
iri_value(right_operand, 'http://www.w3.org/ns/odrl/2/rightOperand').
iri_value(purpose, 'http://www.w3.org/ns/odrl/2/purpose').
iri_value(spatial, 'http://www.w3.org/ns/odrl/2/spatial').
iri_value(eq, 'http://www.w3.org/ns/odrl/2/eq').
iri_value(use, 'http://www.w3.org/ns/odrl/2/use').
iri_value(transfer, 'http://www.w3.org/ns/odrl/2/transfer').

% RDF form of the three policy decisions.
result_rdf(iri(Result), iri('https://example.org/decision'), iri(DecisionIri), default_graph) :-
  policy_decision(Request, decision(Request, Decision, _Details)),
  result_node(Request, Result),
  result_value_iri(Decision, DecisionIri).
result_rdf(iri(Result), iri('https://example.org/duty'), iri(DutyIri), default_graph) :-
  policy_decision(Request, decision(Request, permit, [duty(Duty)])),
  result_node(Request, Result),
  result_value_iri(Duty, DutyIri).
result_rdf(iri(Result), iri('https://example.org/reason'), iri(ReasonIri), default_graph) :-
  policy_decision(Request, decision(Request, deny, [reason(Reason)])),
  result_node(Request, Result),
  result_value_iri(Reason, ReasonIri).

result_node(Request, Result) :-
  atom_concat('https://example.org/result/', Request, Result).
result_value_iri(Value, Iri) :-
  atom_concat('https://example.org/', Value, Iri).

% ISO Prolog helper: print the complete test result as rdf/4 facts.
write_results :-
  result_rdf(S, P, O, G),
  write_term(rdf(S, P, O, G), [quoted(true)]),
  write('.'),
  nl,
  fail.
write_results.
