% Adapted from rdf-prolog-roundtrip.
% This standalone program combines generated RDF input with its ISO Prolog rules.

% Generated by rdf-prolog-roundtrip.

% RDF terms use rdf(Subject, Predicate, Object, Graph).

rdf(iri('https://example.org/bridge'), iri('https://example.org/status'), iri('https://example.org/closed'), default_graph).
rdf(iri('https://example.org/authorityClaim'), iri('http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies'), triple(iri('https://example.org/bridge'), iri('https://example.org/status'), iri('https://example.org/closed')), default_graph).
rdf(iri('https://example.org/authorityClaim'), iri('https://example.org/assertedBy'), iri('https://example.org/transportAuthority'), default_graph).
rdf(iri('https://example.org/authorityClaim'), iri('https://example.org/confidence'), literal('98', datatype('http://www.w3.org/2001/XMLSchema#integer')), default_graph).
rdf(iri('https://example.org/bridge'), iri('https://example.org/status'), iri('https://example.org/open'), default_graph).
rdf(iri('https://example.org/socialClaim'), iri('http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies'), triple(iri('https://example.org/bridge'), iri('https://example.org/status'), iri('https://example.org/open')), default_graph).
rdf(iri('https://example.org/socialClaim'), iri('https://example.org/assertedBy'), iri('https://example.org/anonymousPost'), default_graph).
rdf(iri('https://example.org/socialClaim'), iri('https://example.org/confidence'), literal('35', datatype('http://www.w3.org/2001/XMLSchema#integer')), default_graph).
rdf(iri('https://example.org/transportAuthority'), iri('https://example.org/trustScore'), literal('95', datatype('http://www.w3.org/2001/XMLSchema#integer')), default_graph).
rdf(iri('https://example.org/anonymousPost'), iri('https://example.org/trustScore'), literal('20', datatype('http://www.w3.org/2001/XMLSchema#integer')), default_graph).

% Rank conflicting RDF 1.2 annotated claims by annotation confidence and
% source trust, then derive one auditable bridge-use decision.
%% goal: result_rdf(_, _, _, _)

bridge_status_report(
  report(
    decision(Action),
    evidence(trusted_source(Source), score(Score)),
    ranked_claims(Claims)
  )
) :-
  ranked_claims(Claims),
  bridge_decision(Claims, Action, Source, Score).

ranked_claims(Claims) :-
  findall(
    key(NegativeScore, Status)-claim(Status, Source, score(Score)),
    (
      annotated_status_claim(Status, Source, Score),
      NegativeScore is -Score
    ),
    Unsorted
  ),
  sort(Unsorted, Sorted),
  pair_values(Sorted, Claims).

annotated_status_claim(Status, Source, Score) :-
  status_resource(Status, StatusIri),
  source_resource(Source, SourceIri),
  rdf(
    iri('https://example.org/bridge'),
    iri('https://example.org/status'),
    iri(StatusIri),
    default_graph
  ),
  rdf(
    Reifier,
    iri('http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies'),
    triple(
      iri('https://example.org/bridge'),
      iri('https://example.org/status'),
      iri(StatusIri)
    ),
    default_graph
  ),
  rdf(
    Reifier,
    iri('https://example.org/assertedBy'),
    iri(SourceIri),
    default_graph
  ),
  rdf_number(Reifier, 'https://example.org/confidence', Confidence),
  rdf_number(iri(SourceIri), 'https://example.org/trustScore', Trust),
  Score is Confidence * Trust.

bridge_decision(
  [claim(Status, Source, score(Score))|_],
  Action,
  Source,
  Score
) :-
  Score >= 8000,
  status_action(Status, Action).
bridge_decision(
  [claim(_Status, _Source, score(Score))|_],
  verify_manually,
  no_trusted_source,
  Score
) :-
  Score < 8000.
bridge_decision([], verify_manually, no_trusted_source, 0).

rdf_number(Subject, PredicateIri, Number) :-
  rdf(
    Subject,
    iri(PredicateIri),
    literal(Text, datatype(_Datatype)),
    default_graph
  ),
  atom_chars(Text, Chars),
  number_chars(Number, Chars).

pair_values([], []).
pair_values([_Key-Value|Pairs], [Value|Values]) :-
  pair_values(Pairs, Values).

status_action(closed, avoid_bridge).
status_action(open, cross_bridge).

status_resource(closed, 'https://example.org/closed').
status_resource(open, 'https://example.org/open').
source_resource(transport_authority, 'https://example.org/transportAuthority').
source_resource(anonymous_post, 'https://example.org/anonymousPost').

% RDF form of the bridge decision and the ranked evidence.
result_rdf(iri('https://example.org/bridge'), iri('https://example.org/decision'), iri(DecisionIri), default_graph) :-
  bridge_status_report(report(decision(Action), _Evidence, _Claims)),
  atom_concat('https://example.org/', Action, DecisionIri).
result_rdf(iri('https://example.org/bridge'), iri('https://example.org/trustedSource'), iri(SourceIri), default_graph) :-
  bridge_status_report(report(_Decision, evidence(trusted_source(Source), _Score), _Claims)),
  source_result_iri(Source, SourceIri).
result_rdf(iri('https://example.org/bridge'), iri('https://example.org/score'), literal(ScoreText, datatype('http://www.w3.org/2001/XMLSchema#integer')), default_graph) :-
  bridge_status_report(report(_Decision, evidence(_Source, score(Score)), _Claims)),
  number_atom(Score, ScoreText).
result_rdf(iri(StatusIri), iri('https://example.org/rank'), literal(RankText, datatype('http://www.w3.org/2001/XMLSchema#integer')), default_graph) :-
  bridge_ranked_claim(Rank, Status, _Source, _Score),
  status_resource(Status, StatusIri), number_atom(Rank, RankText).
result_rdf(iri(StatusIri), iri('https://example.org/assertedBy'), iri(SourceIri), default_graph) :-
  bridge_ranked_claim(_Rank, Status, Source, _Score),
  status_resource(Status, StatusIri), source_resource(Source, SourceIri).
result_rdf(iri(StatusIri), iri('https://example.org/score'), literal(ScoreText, datatype('http://www.w3.org/2001/XMLSchema#integer')), default_graph) :-
  bridge_ranked_claim(_Rank, Status, _Source, Score),
  status_resource(Status, StatusIri), number_atom(Score, ScoreText).

bridge_ranked_claim(Rank, Status, Source, Score) :-
  bridge_status_report(report(_Decision, _Evidence, ranked_claims(Claims))),
  ranked_claim(Claims, 1, Rank, Status, Source, Score).
ranked_claim([claim(Status, Source, score(Score))|_], Rank, Rank, Status, Source, Score).
ranked_claim([_|Rest], N, Rank, Status, Source, Score) :-
  Next is N + 1,
  ranked_claim(Rest, Next, Rank, Status, Source, Score).
source_result_iri(no_trusted_source, 'https://example.org/noTrustedSource').
source_result_iri(Source, Iri) :- source_resource(Source, Iri).
number_atom(Number, Atom) :- number_chars(Number, Chars), atom_chars(Atom, Chars).

% ISO Prolog helper: print the complete test result as rdf/4 facts.
write_results :-
  result_rdf(S, P, O, G),
  write_term(rdf(S, P, O, G), [quoted(true)]),
  write('.'),
  nl,
  fail.
write_results.
