% Adapted from rdf-prolog-roundtrip.
% This standalone program combines generated RDF input with its ISO Prolog rules.

% Generated by rdf-prolog-roundtrip.

% RDF terms use rdf(Subject, Predicate, Object, Graph).

rdf(iri('https://example.org/sensorGraph'), iri('https://example.org/reportedBy'), iri('https://example.org/station7'), default_graph).
rdf(iri('https://example.org/sensor1'), iri('https://example.org/temperature'), literal('21.5', datatype('http://www.w3.org/2001/XMLSchema#string')), iri('https://example.org/sensorGraph')).

% Join graph metadata in the default graph with data from the named graph.
result_rdf(S, iri('https://example.org/reportedBy'), Station, default_graph) :-
  rdf(
    iri('https://example.org/sensorGraph'),
    iri('https://example.org/reportedBy'),
    Station,
    default_graph
  ),
  rdf(
    S,
    iri('https://example.org/temperature'),
    _,
    iri('https://example.org/sensorGraph')
  ).
%% goal: result_rdf(_, _, _, _)

% ISO Prolog helper: print the complete test result as rdf/4 facts.
write_results :-
  result_rdf(S, P, O, G),
  write_term(rdf(S, P, O, G), [quoted(true)]),
  write('.'),
  nl,
  fail.
write_results.
